# Generated by Django 2.1.2 on 2019-06-12 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedzonkorecipe',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 6, 12, 13, 19, 49, 895280), editable=False),
        ),
    ]
