# Generated by Django 2.1.2 on 2019-06-12 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_auto_20190612_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedzonkorecipe',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 6, 12, 11, 21, 51, 83559, tzinfo=utc), editable=False),
        ),
    ]
