# Generated by Django 2.1.2 on 2019-06-12 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_auto_20190612_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedzonkorecipe',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
