# Generated by Django 2.1.2 on 2019-06-12 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0006_auto_20190612_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedzonkorecipe',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 6, 12, 11, 24, 4, 284434, tzinfo=utc)),
        ),
    ]
