# Generated by Django 2.1.2 on 2019-06-12 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0008_auto_20190612_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedzonkoplan',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
