# Generated by Django 2.1.2 on 2019-06-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0009_auto_20190612_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedzonkorecipe',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jedzonkorecipe',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
