# Generated by Django 2.2.2 on 2019-06-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0010_auto_20190612_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='jedzonkorecipe',
            name='preparation_method',
            field=models.TextField(default=''),
        ),
    ]
