# Generated by Django 2.2.2 on 2019-06-13 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0011_jedzonkorecipe_preparation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedzonkorecipe',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='jedzonkorecipe',
            name='updated',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
