# Generated by Django 2.1.2 on 2019-06-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0011_auto_20190613_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedzonkorecipe',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jedzonkorecipe',
            name='updated',
            field=models.DateField(),
        ),
    ]
