# Generated by Django 2.1.2 on 2019-06-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0012_auto_20190613_2216'),
        ('jedzonko', '0013_auto_20190613_2053'),
    ]

    operations = [
    ]
