# Generated by Django 2.1.2 on 2019-06-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0014_merge_20190617_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedzonkorecipe',
            name='votes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
